services:
  database:
    image: postgres:16-alpine
    container_name: prueba_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 104462
      POSTGRES_DB: prueba_database4
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: